### ISSUE TITLE
No support for macOS in Package.swift

### ISSUE THREAD

**Issue by fjtrujy** [microsoft/onnxruntime-swift-package-manager#5]
Currently, the package just supports iOS `platforms: [.iOS(.v11)],`, what's blocking us for not allowing it for `.macOS` as well?

Cheers.

**Comment by anthonydito** [comment]
Agree! Would be great to have support for MacOS as well. Is this possible, or any guide for how to do this?

**Comment by anthonydito** [comment]
@YUNQIUGUO @edgchen1 - would you have any feedback about how to do this in a fork? Seems that some of the dependencies are iOS only

**Comment by YUNQIUGUO** [comment]
hi thanks for raising this issue.

Currently, we don't distribute pod binary targets for macOS yet. Adding macOS support is on ORT 1.17 task list. 

After that, hopefully it will be easy to configure macOS platform apart from iOS here in Package.swift and pointing to the macOS pod binary target, etc.

**Comment by YUNQIUGUO** [comment]
Close this issue as now macOS is officially supported in Package.swift now.

Please reopen the issue if there's any questions.

**Comment by fjtrujy** [comment]
Hello @YUNQIUGUO , could you please make a new release then? currently, the only way is pointing to `main/master` which is not the best approach.

Cheers
